# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('publisher', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feedname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('articles', models.ManyToManyField(to='feeder.Article')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('feeds', models.ManyToManyField(to='feeder.Feed')),
            ],
        ),
    ]
